CREATE TABLE  IF NOT EXISTS contacts (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	contact_id INTEGER NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	status VARCHAR(20) DEFAULT 'active',
	CONSTRAINT  unique_contact UNIQUE (user_id, contact_id),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (contact_id) REFERENCES users(id) ON DELETE CASCADE	
)